export const tableDict: { [key: string]: string } = {
    id: 'ID',
    playerID: 'Player ID',
    birthYear: 'Birth Year',
    birthMonth: 'Birth Month',
    birthDay: 'Birthday',
    birthCity: 'Birth City',
    birthCountry: 'Birth Country',
    birthState: 'Birth State',
    deathYear: 'Death Year',
    deathMonth: 'Death Month',
    deathDay: 'Death Day',
    deathCountry: 'Death Country',
    deathState: 'Death State',
    deathCity: 'Death City',
    nameFirst: 'First Name',
    nameLast: 'Last Name',
    nameGiven: 'Given Name',
    weight: 'Weight',
    height: 'Height',
    bats: 'Bats',
    throws: 'Throws',
    debut: 'Debut',
    bbrefID: 'BBRef ID',
    finalGame: 'Final Game',
    retroID: 'Retro ID',
}
