export const style = {
    pageCard: "mt-40 ml-auto mr-auto  justify-center max-w-3xl max-h-xl bg-white shadow rounded-lg  flex flex-col mb-40 ",
    innerCard: 'm-auto  w-full h-full p-8',
    h1: "text-4xl sm:text-5xl text-center sm:text-left font-bold ",
    h2: 'text-2xl sm:text-2xl font-bold mt-4 mb-4',
    p: "mt-4 mb-4 text-lg sm:text-xl text-center sm:text-left transition-all duration-2000 ease-in-out transform ",
    smallP: "mt-4 mb-4 text-left  ",
    ul: "mt-4 mb-4 list-disc list-inside ",
    searchBoxOuter: "flex flex-row gap-4 items-center sm:items-start w-full transition-all duration-2000 ease-in-out transform mb-8 ",
    searchField: "w-full p-2 text-lg border-2 border-gray-300 focus:outline-none focus:border-red-800 rounded-lg ",
    searchButtonActive: "p-2 bg-blue-300 hover:bg-gray-800 text-white rounded-lg self-stretch transition-all duration-2000 ease-in-out transform ",
    searchButton: "p-2 bg-red-800 hover:bg-gray-800 text-white rounded-lg self-stretch transition-all duration-2000 ease-in-out transform ",
    pleaseWait: "mt-10 w-full flex flex-col gap-4 items-center ",
    hr: "w-full border-gray-300",
    pastQueries: "cursor-pointer bg-white p-4 shadow-lg rounded-lg hover:bg-gray-200 ",
    statSectionDiv: "mb-4",
    a: "text-blue-500",
    tableDiv: 'overflow-x-auto w-full shadow rounded-lg mb-4 mt-4',
    table: 'border-collapse text-left w-full',
    tableHeader: 'border-collapse p-4 text-left font-bold ',
    tableRow: '',
    tableClickHeader: 'hover:text-blue-500 cursor-pointer font-bold text-left ',
    cell: 'border-collapse pl-4 pr-4 pt-2 pb-2 text-left whitespace-nowrap',
    header: "grid grid-cols-3 w-full gap-4 fixed top-0 z-50 ",
    headerDisclosure: "bg-red-800 bg-opacity-100 text-white w-screen ",
    headerDisclosureInner: "mx-auto px-2 sm:px-6 lg:px-8 relative flex h-16 items-center justify-between ",
    headerMobile: "absolute inset-y-0 left-0 flex items-center sm:hidden ",
    headerMobileButton: "group relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white",
    headerNavArea: "flex flex-1 items-center justify-center sm:items-stretch sm:justify-start",
    headerMenu: "flex flex-shrink-0 items-center",
    headerMenuButton: "relative flex flex-col",
    headerMenuItems: "absolute left-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 transition focus:outline-none data-[closed]:scale-95 data-[closed]:transform data-[closed]:opacity-0 data-[enter]:duration-100 data-[leave]:duration-75 data-[enter]:ease-out data-[leave]:ease-in",
    headerMenuItem: "block px-4 py-2 text-sm text-gray-700 data-[focus]:bg-gray-100",
    siteTitleContainer: "hidden sm:ml-6 sm:block",
    siteTitleDiv: "flex space-x-4",
    siteTitle: "text-white hover:bg-red-900 hover:text-white px-3 py-2 rounded-md text-sm font-medium",
    siteTitleFont: "text-2xl font-bold font-[family-name:var(--font-geist-sans)]",
    profileAreaDiv: "absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0",
    profileMenuDiv: "relative ml-3",
    profileButton: "relative rounded-full p-1 hover:outline-black hover:bg-red-900 transition-colors duration-100 ease-in-out",
    profileIcon: "text-white h-6 w-6 transition-colors duration-100 ease-in-out hover:text-white",
    profileMenuItems: "absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 transition focus:outline-none data-[closed]:scale-95 data-[closed]:transform data-[closed]:opacity-0 data-[enter]:duration-100 data-[leave]:duration-75 data-[enter]:ease-out data-[leave]:ease-in",
    profileMenuItem: "block px-4 py-2 text-sm text-gray-700 data-[focus]:bg-gray-100 cursor-pointer",
    searchResultsDiv: "text-2xl sm:text-2xl text-center sm:text-left font-bold transition-all duration-2000 ease-in-out transform bg-white p-4 shadow-lg rounded-lg",
    searchResults: "mt-4 w-full",
    similarQueriesDiv: ''
}

